name: taoju5_bc
description: A new Flutter package project.
version: 0.0.1
author:
homepage:
publish_to: none
environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_screenutil: ^5.0.0
  dio: ^4.0.0
  flutter_swiper_null_safety:
    git: https://github.com/lianyagang/flutter_swiper_null_safety.git
  # dio: 3.0.10
  # dio_http_cache: ^0.2.11 
  shared_preferences: ^2.0.5
  device_info: ^2.0.0
  package_info: ^2.0.0
  connectivity: ^3.0.3
  flutter_staggered_animations: ^1.0.0
  # get: ^3.26.0
  get: ^4.1.4
  logger: ^1.0.0
  path_provider: ^2.0.1
  flutter_bugly: ^0.3.1
  cached_network_image: ^3.0.0
  animations: ^2.0.0
  flutter_easyloading: ^3.0.0
  # pull_to_refresh: 1.6.3
  pull_to_refresh: 1.6.4-nullsafety.0
  azlistview: ^2.0.0-nullsafety.0
  photo_view: ^0.11.1
  # flutter_datetime_picker: ^1.4.0
  # flutter_swiper: ^1.1.6
  # device_preview: ^0.5.5
  # json_annotation: ^3.1.1
  # webview_flutter: ^1.0.7
  flutter_html: ^2.0.0-nullsafety.0
  flutter_app_upgrade: ^1.1.0
  # webview_flutter: ^2.0.2
  flutter_staggered_grid_view: ^0.4.0
  shimmer: ^2.0.0
  # jpush_flutter: ^0.6.3
  permission_handler: ^6.1.1
  scan: ^1.0.0
  # install_plugin: ^2.0.1
  # fair: ^0.2.0
  flare_flutter: ^3.0.0
  fluwx: ^3.4.1
  multi_image_picker: ^4.7.15
  image_picker: ^0.7.4
  flutter_slidable: ^0.6.0
  autolist:
    git: https://github.com/ME-smile/autolist.git
  syncfusion_flutter_charts: ^19.1.56
  # sqflite: ^1.3.2+4
  # dokit: ^0.2.14
  # geolocator: ^6.2.1
  # amap_location: ^0.2.0
  carousel_slider: ^4.0.0-nullsafety.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
