name: taoju5
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.3.1+2021

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_screenutil: ^4.0.0-beta2
  dio: ^3.0.10
  dio_http_cache: ^0.2.11 
  shared_preferences: ^0.5.12+4
  device_info: ^1.0.0
  package_info: ^0.4.3+4
  connectivity: ^2.0.2
  flutter_staggered_animations: ^0.1.2
  get: ^3.26.0
  logger: ^0.9.4
  path_provider: ^1.6.24
  flutter_bugly: ^0.3.1
  cached_network_image: ^2.3.3
  animations: ^1.1.2
  flutter_easyloading: ^2.2.2
  pull_to_refresh: 1.6.3
  azlistview: ^1.0.2
  photo_view: ^0.10.3
  flutter_datetime_picker: ^1.4.0
  flutter_swiper: ^1.1.6
  device_preview: ^0.5.5
  json_annotation: ^3.1.1
  # webview_flutter: ^1.0.7
  flutter_html: ^1.2.0
  flutter_app_upgrade: ^1.1.0
  flutter_staggered_grid_view: ^0.3.3
  shimmer: ^1.1.2
  # jpush_flutter: ^0.6.3
  permission_handler: ^5.1.0+2
  scan: 0.0.7
  # install_plugin: ^2.0.1
  # fair: ^0.2.0
  flare_flutter: ^2.0.6
  fluwx: ^2.6.2
  multi_image_picker: ^4.7.15
  flutter_slidable: ^0.5.7
  autolist: ^0.1.1
  syncfusion_flutter_charts: ^18.4.47
  sqflite: ^1.3.2+4
  dokit: ^0.2.14
  geolocator: ^6.2.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
      - assets/images/
      - assets/images/2.0x/
      - assets/images/3.0x/
      - assets/images/curtain/
      - assets/flrs/
      - assets/data/curtain_mode.json
  fonts:
  # - family: Quicksand
  #   fonts:
  #     - asset: assets/fonts/Quicksand-Medium.ttf
  #       style: normal
  #     - asset: assets/fonts/Quicksand_Bold.otf
  #       weight: 700

  # - family: Raleway
  #   fonts:
  #     - asset: assets/fonts/Raleway-Regular.ttf
  #       style: normal
  #     - asset: assets/fonts/Raleway-Medium.ttf
    - family: Taojuwu
      fonts:
        - asset: assets/fonts/iconfont.ttf
  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
